language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud: true

script:
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jowi20 -Dsonar.login=$SONAR_TOKEN -X
  - pytest

notifications:
  slack: entornodeinte-7kl4185:OnZhSXGPrVTsAaM4xsp28SXY


before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: 
    secure: d31376e4-a904-4cd7-9872-b9afb6cd3084
  app: myapp
  on:
    repo: Jowi20/2doEntornoIC
